ENTRY_GATE:
  "1":
    "TwoWheeler":
      [
        A01,
        A02,
        A03,
        A04
      ]
    "FourWheeler":
      [
        C01,
        C02,
        C03,
        C04
      ]
  "2":
    "TwoWheeler":
      [
        B01,
        B02,
        B03,
        B04
      ]
    "FourWheeler":
      [
        D01,
        D02,
        D03,
        D04
      ]