ENTRY_GATE:
  "1":
    "TwoWheeler":
      [
        A01,
        A02,
        A03,
        A04
      ]
    "FourWheeler":
      [
        C01,
        C02,
        C03,
        C04
      ]
  "2":
    "TwoWheeler":
      [
        B01,
        B02,
        B03,
        B04
      ]
    "FourWheeler":
      [
        D01,
        D02,
        D03,
        D04
      ]
  "3":
    "TwoWheeler":
      [
        A05,
        A06,
        A07,
        A08
      ]
    "FourWheeler":
      [
        C05,
        C06,
        C07,
        C08
      ]
  "4":
    "TwoWheeler":
      [
        B05,
        B06,
        B07,
        B08
      ]
    "FourWheeler":
      [
        D05,
        D06,
        D07,
        D08
      ]